version: '3.8'

services:
  db:
    image: mysql:1
    environment:
      MYSQL_ROOT_PASSWORD: adios
      MYSQL_DATABASE: hola
    volumes:
      - /patatin:/patatan

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: "node app.js"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: manzana
      DB_USER: pera
      DB_PASSWORD: tomate
      DB_NAME: limon

  adminer:
    image: blablabla
    ports:
      - "8080:8080"

volumes:
  datos_mysql:
