version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
    volumes:
      - datos_mysql:/var/lib/mysql

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: "node app.js"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: prueba

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  datos_mysql: